language: c
dist: trusty
compiler:
  - gcc
os:
  - linux

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "i5wXM5UGRLxlcO+4Q+l3UjTka7mDE6wCD0gyU9LXVzMD5yACHKRQ2XQFVviMvBp5oXL3aBxnbZh1TdkzkI4+XIvMIPCwNQf0vpEclQ/zCdJtVZAA2G2dC/DL4RbPGN0ad5vLJCgmuOP5BqOpoIeC0+GLnmpRwcqNf9yeeaDqxLiGt24SFplPvwNnEDDUn2X8TiSfTh962utqO5UIgonWvTX1RVN4jLUl+G98inSZYuG0+oRmvb26PBqhkSRFVK1spbxoFQi15ySgmNKFTo9Miqq3VPxKLnVhEIrSY2pUW8swu+9d7+YYJUxO9w4WL4xLQqXiX/SXLr4jpaK0FS1otlT8zjlasTLGBfIYTZoE9pUz4h2R2vFPkiGkQGKHZHlPwqshy33w7IjwYJV41qvgpo0LYUj23rQ1LE24wbVpt1Nz+TQJaX7307nWrSaXYw9oYh2e32M1NPGZNFrEWvtmTZlyC6TFCwXtwFyzdLWhFfXO4U/bFcqKL00grtIzotSq+pdFVI2VFeDpepDAettYKYWEOv17GdlreQ53xtFCjmbH+IBkxH1JuFkk+uXYMR4Y7ramCA2aTppcteu7GB6dePfiHQDc2lrYyFUp58pQB3StDBUrAndbj3AwQRiF+6WKo7Z93aE1IWcmUESMxC4wFl76Tq4ESJR+a8Xq+aNZ+NE="
   - LD_LIBRARY_PATH=/tmp/nemea/lib


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-multilib
      - gcc
      - g++
      - autoconf
      - pkg-config
      - make
      - automake
      - libxml2-dev
      - libxml2
      - python
      - python-dev
      - python-pip
  coverity_scan:
    project:
      name: "CESNET/Nemea-Framework"
      description: "Build submitted via Travis CI"
    notification_email: cejkat@cesnet.cz
    build_command_prepend: "./bootstrap.sh; ./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity

install:
   - pyenv install 2.7.10

script:
  - python -c 'import sys; print(sys.path)'
  - python -V
  - pyenv versions || echo "pyenv not found"
  - pyenv global 2.7.10
  - export PATH=$(pyenv prefix)/bin:$PATH
  - echo PATH=$PATH
  - ./bootstrap.sh && ./configure --prefix=/usr && make clean && sudo make install &&
    (cd pytrap && $(pyenv which python) setup.py install;)
  - (cd pytrap && ./test.sh;)

